Repository size-up/freegamescatcher-core, pull requests merged in 2022-10, with the labels that each got.

#23 Feat/mailsender with template
  .vscode/launch.json
  data/cache.epicgames.json
  data/cache.json
  package.json
  src/app.ts
  src/helpers/mappers/epic-games.mapper.ts
  src/interfaces/client.interface.ts
  src/interfaces/data.interface.ts
  src/services/client.service.ts
  src/services/emailSender.service.ts
  src/templates/email.epicgames.template.hbs
  yarn.lock
Labels: enhancement

#33 ✨ Google drive implementation
  README.md
  package.json
  src/app.ts
  src/helpers/mappers/epic-games.mapper.ts
  src/inputs/http/receiver.controller.ts
  src/interfaces/cache.interface.ts
  src/interfaces/client.interface.ts
  src/interfaces/data.interface.ts
  src/outputs/epic-games/client.ts
  src/outputs/google/drive.ts
  src/services/client.service.ts
  src/services/data.service.ts
  src/services/emailSender.service.ts
  src/services/epicGames.service.ts
  yarn.lock
Labels: enhancement

#34 🐛 Export version to image
  .github/workflows/onPushMainPrMain.yaml
  Dockerfile
  src/app.ts
  src/config/information.ts
  src/config/logger.ts
Labels: bug, ci/cd

#36 :bug: Revert "🔧 Optimize `VERSION` env. variable"
  .github/workflows/onPushMainPrMain.yaml
  Dockerfile
Labels: bug

#45 :bug: Fix UUID: if wrong, the entire content file `receivers.json` was removed
  src/services/data.service.ts
  src/templates/email.template.hbs
Labels: bug

#46 :bug: Fix to save email template in the `build` directory
  package.json
Labels: bug

#47 🐛 Add `prep` env. with `environment` logger field
  .github/workflows/onPushMainPrMain.yaml
  .vscode/launch.json
  Dockerfile
  src/config/logger.ts
Labels: bug

#50 🧱 Add the `-core` suffix
  .github/workflows/onPushMainPrMain.yaml
  CHANGELOG.md
  README.md
  package.json
Labels: ci/cd

#54 :bug: Fix/payed games in email
  src/helpers/mappers/epic-games.mapper.ts
  src/interfaces/client.interface.ts
  src/outputs/epic-games/client.ts
  src/services/client.service.ts
Labels: bug

#53 📄 Add `GNU GPLv3` license
  LICENSE
  package.json
Labels: documentation

#62 ✨ Significant refactor, renaming, optimization and new tests
  data/cache.epicgames.json
  data/example.json
  data/receivers.json
  package.json
  src/app.ts
  src/config/application.config.ts
  src/config/logger.config.ts
  src/config/security.config.ts
  src/facade/core.facade.ts
  src/helpers/epic.games.mapper.ts
  src/inputs/controllers/application.controller.ts
  src/inputs/controllers/receiver.controller.ts
  src/middlewares/default.middleware.ts
  src/middlewares/error.middleware.ts
  src/outputs/emailer/emailer.output.ts
  src/outputs/epic-games/epic.games.output.ts
  src/outputs/google/drive.output.ts
  src/services/application.service.ts
  src/services/data.service.ts
  src/services/email.service.ts
  src/services/epicGames.service.ts
  src/services/game.service.ts
  src/services/receiver.service.ts
  test/config/application.config.test.ts
  test/helpers/epic.games.mapper.test.ts
  test/services/data.service.test.ts
  test/services/game.service.test.ts
Labels: enhancement

#65 💚 Remove deploy prod. overlap
  .github/workflows/onPushMainPrMain.yaml
Labels: ci/cd
