Repository size-up/freegamescatcher-core, pull requests merged in 2023-03, with the labels that each got.

#98 👷 Disable release job if it's triggered by a merge_group event and allow manual trigger
  .github/workflows/onPushMainPrMain.yaml
Labels: ci/cd

#99 ⚡️ `DKIM` email signature mecanism
  README.md
  src/interfaces/email.interface.ts
  src/services/email.service.ts
Labels: enhancement

#101 🐛 Iterate on `upcomingPromotionalOffers` field to find future free games
  src/services/game.service.ts
  test/data/games.json
  test/services/game.service.test.ts
Labels: bug

#78 👷 Extract branch name to build branch name image
  .github/workflows/onPushMainPrMain.yaml
Labels: ci/cd

#108 💚 Use current branch name when head reference is empty
  .github/workflows/onPushMainPrMain.yaml
Labels: bug, ci/cd

#110 💚 Enhance and fix extract branch name step
  .github/workflows/onPushMainPrMain.yaml
Labels: bug, ci/cd

#111 👷 Disable build and push image job if is dependabot
  .github/workflows/onPushMainPrMain.yaml
Labels: enhancement, ci/cd

#119 :arrow_up: Upgrade deps using Dependabot's PRs
  package.json
  yarn.lock
Labels: dependencies

#126 🐛 Be aware about `main` branch in bash script extract branch name
  .github/workflows/ci-cd.yaml
Labels: bug, ci/cd
